server:
  port: 7106
spring:
  application:
    name: property-owner-service
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB_NAME:picma_owners}
  cloud:
    stream:
      function:
        definition: handleLeadStatusChanged;handleQuoteAccepted;handleQuoteRejected
      bindings:
        handleLeadStatusChanged-in-0:
          destination: picma.leads.status
          group: property-owner-service-group
        handleQuoteAccepted-in-0:
          destination: picma.quotes.accepted
          group: property-owner-service-group
        handleQuoteRejected-in-0:
          destination: picma.quotes.rejected
          group: property-owner-service-group
eureka:
  client:
    service-url:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8761}/eureka/
  instance:
    hostname: ${REGISTRY_HOST:localhost}
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: ${REGISTRY_PREFER_IP:true}