spring:
  application:
    name: user-authnz-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: dai-ichi-insurer
            client-secret: WJmbj3fln4LK1sHr9xh2b7y8Eum9iXWc
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/"
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/picma
            token-uri: http://localhost:8081/realms/picma/protocol/openid-connect/token
server:
  port: ${APP_PORT:5052}