spring:
  application:
    name: user-authnz-service
  data:
    redis:
      host: ${PICMA_CACHE_HOST:localhost}
      port: ${PICMA_CACHE_PORT:6379}
      password: ${PICMA_CACHE_PASSWORD:password}
      username: ${PICMA_CACHE_USERNAME:username}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: dai-ichi-insurer
            client-secret: WJmbj3fln4LK1sHr9xh2b7y8Eum9iXWc
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/"
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/picma
            token-uri: http://localhost:8081/realms/picma/protocol/openid-connect/token
server:
  port: ${APP_PORT:5052}
eureka:
  client:
    service-url:
      default-zone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8761}/eureka/
  instance:
    hostname: ${AUTHNZ_HOST:localhost}
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"