spring:
  application:
    name: notification-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:picma_notifications}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cloud:
    stream:
      function:
        definition: handleLeadCreated;handleLeadStatusChanged;handleQuoteCreated;handleQuoteAccepted;handleQuoteRejected;handleNotification
      bindings:
        handleLeadCreated-in-0:
          destination: picma.leads.created
          group: notification-service-group
        handleLeadStatusChanged-in-0:
          destination: picma.leads.status
          group: notification-service-group
        handleQuoteCreated-in-0:
          destination: picma.quotes.created
          group: notification-service-group
        handleQuoteAccepted-in-0:
          destination: picma.quotes.accepted
          group: notification-service-group
        handleQuoteRejected-in-0:
          destination: picma.quotes.rejected
          group: notification-service-group
        handleNotification-in-0:
          destination: picma.notifications
          group: notification-service-group

picma:
  services:
    user-mgmt-service:
      url: http://${USER_MGMT_HOST:localhost}:${USER_MGMT_PORT:5051}

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 7105

eureka:
  client:
    service-url:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8761}/eureka/
  instance:
    hostname: ${REGISTRY_HOST:localhost}
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: ${REGISTRY_PREFER_IP:true}