spring:
  application:
    name: property-quote-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:property_quote_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _QUOTE
            audit_table_prefix: AU_PROPERTY
            revision_field_name: rev_id
            revision_type_field_name: rev_type
            store_data_at_delete: true
  kafka:
    bootstrap-servers: ${BROKER_HOST:localhost}:${BROKER_PORT:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 7102
picma:
  properties:
    lead:
      topic: ${LEADS_TOPIC_NAME:property-lead}
      partitions: ${LEADS_TOPIC_PARTITIONS:1}
    management:
      base-uri: http://${PROPERTY_MGMT_HOST:localhost}:${PROPERTY_MGMT_PORT:7101}
    agent:
      base-uri: http://${PROPERTY_AGENT_HOST:localhost}:${PROPERTY_AGENT_PORT:7104}