spring:
  application:
    name: property-quote-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:property_quote_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _QUOTE
            audit_table_prefix: AU_PROPERTY
            revision_field_name: rev_id
            revision_type_field_name: rev_type
            store_data_at_delete: true
server:
  port: 7102