spring:
  application:
    name: property-quote-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:property_quote_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 7102

picma:
  properties:
    lead:
      base-uri: http://${PROPERTY_LEAD_HOST:localhost}:${PROPERTY_LEAD_PORT:7103}
    management:
      base-uri: http://${PROPERTY_MGMT_HOST:localhost}:${PROPERTY_MGMT_PORT:7101}
    agent:
      base-uri: http://${PROPERTY_AGENT_HOST:localhost}:${PROPERTY_AGENT_PORT:7104}
