spring:
  application:
    name: user-mgmt-service
  security:
    oauth2:
      client:
        registration:
          keycloak-admin:
            provider: keycloak
            client-id: user-mgmt-client
            client-secret: zJruEZzWjp6rdKgcLtccU0eEfc2O0w3v
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: http://${IDP_HOST:localhost}:${IDP_PORT:8081}/realms/${IDP_REALMS:picma}/protocol/openid-connect/token
picma:
  iam:
    usersApi: ${PROTOCOL:http}://${IDP_HOST:localhost}:${IDP_PORT:8081}/admin/realms/${IDP_REALMS:picma}/users
    groupsApi: ${PROTOCOL:http}://${IDP_HOST:localhost}:${IDP_PORT:8081}/admin/realms/${IDP_REALMS:picma}/groups
    groups:
      owners: ${OWNERS_GROUP_ID:d41e9d41-afb7-408e-bbd0-970b093268ab}
      agents: ${AGENTS_GROUP_ID:2a576f8b-ee0d-4c57-be7a-de4a490e298d}
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${REGISTRY_PORT:8761}/eureka/
  instance:
    hostname: ${REGISTRY_HOST:localhost}
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: ${REGISTRY_PREFER_IP:false}
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: ${APP_PORT:5051}