server:
  port: 7107

spring:
  application:
    name: deep-research-service
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:password}
    mongodb:
      host: localhost
      port: 27017
      database: picma
  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY:AIzaSyDwCinXYhYeobE38oZiL_o8DEPAHuZh_As}
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.7

eureka:
  client:
    service-url:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8761}/eureka/
  instance:
    hostname: ${REGISTRY_HOST:localhost}
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: ${REGISTRY_PREFER_IP:true}