spring:
  application:
    name: property-mgmt-service
  data:
    mongodb:
      host: ${PROPERTIES_HOST:localhost}
      database: ${PROPERTIES_DB:picma}
      port: ${PROPERTIES_PORT:27017}
      auto-index-creation: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
picma:
  data:
    mongodb:
      collection: ${COLLECTION_NAME:property_management}
server:
  port: 7101
eureka:
  client:
    service-url:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8761}/eureka/
  instance:
    hostname: ${REGISTRY_HOST:localhost}
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: ${REGISTRY_PREFER_IP:true}