spring:
  application:
    name: property-mgmt-service
  data:
    mongodb:
      host: ${PROPERTIES_HOST:localhost}
      database: ${PROPERTIES_DB:picma}
      port: ${PROPERTIES_PORT:27017}
      auto-index-creation: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
properties:
  management:
    collection:
      name: ${COLLECTION_NAME:property_management}
server:
  port: 7101