spring:
  application:
    name: property-mgmt-service
  data:
    mongodb:
      host: ${PROPERTIES_HOST:localhost}
      database: ${PROPERTIES_DB:picma}
      port: ${PROPERTIES_PORT:27017}
      auto-index-creation: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:}
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
properties:
  management:
    collection:
      name: ${COLLECTION_NAME:property_management}
server:
  port: 7101