spring:
  application:
    name: iden-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/picma
  cloud:
    gateway:
      server:
        webflux:
          enabled: true
          discovery:
            locator:
              enabled: true
          filter:
            local-response-cache:
              enabled: true
          routes:
            #            - id: userMgmt-getAllUsers-route
            #              predicates:
            #                - Path=/picma/users/**
            #              uri: lb://USER-MGMT-SERVICE
            #              filters:
            #                - RewritePath=/picma/users/?(?<segment>.*),/users/$\{segment}
            #                - AddRequestHeader=userType,owner
            - id: userMgmt-documents-route-01
              predicates:
                - Path=/swagger-ui.html
              uri: lb://USER-MGMT-SERVICE
            - id: userMgmt-documents-route-02
              predicates:
                - Path=/swagger-ui/**
              uri: lb://USER-MGMT-SERVICE
            - id: userMgmt-documents-route-03
              predicates:
                - Path=/v3/**
              uri: lb://USER-MGMT-SERVICE
            - id: userAuthNZ-token-route
              predicates:
                - Path=/login/**
              uri: lb://USER-AUTHNZ-SERVICE
              filters:
                - RewritePath=/login/?(?<segment>.*), /token/$\{segment}
server:
  port: 6060
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
eureka:
  client:
    service-url:
      default-zone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8761}/eureka/
    fetch-registry: true
  instance:
    hostname: ${IG_HOST:localhost}
    instance-id: ${spring.application.name}:${server.port}
#logging:
#  file:
#    path: .picma-storage/picma-ig-logs
#  level:
#    root: debug