spring:
  application:
    name: iden-gateway
server:
  port: 6060
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
eureka:
  client:
    service-url:
      default-zone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8761}/eureka/
    fetch-registry: true
  instance:
    hostname: ${IG_HOST:localhost}
    instance-id: ${spring.application.name}:${server.port}