spring:
  application:
    name: properties-mgmt-service
  data:
    mongodb:
      host: ${PROPERTIES_HOST:localhost}
      database: ${PROPERTIES_DB:picma}
      port: ${PROPERTIES_PORT:27017}
      auto-index-creation: true
server:
  port: 7100
properties:
  management:
    collection:
      name: ${COLLECTION_NAME:properties_management}