spring:
  application:
    name: property-lead-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:property_lead_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 7103
eureka:
  client:
    service-url:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8761}/eureka/
  instance:
    hostname: ${REGISTRY_HOST:localhost}
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: ${REGISTRY_PREFER_IP:true}