spring:
  application:
    name: property-agent-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:picma_users}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      bootstrap-servers: ${BROKER_HOST:localhost}:${BROKER_PORT:9092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: lead-group
    producer:
      bootstrap-servers: ${BROKER_HOST:localhost}:${BROKER_PORT:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  cloud:
    stream:
      function:
        definition: handleLeadCreated
      bindings:
        handleLeadCreated-in-0:
          destination: picma.leads.created
          group: property-agent-service-group
management:
  endpoints:
    web:
      exposure:
        include: "*"
picma:
  services:
    property-lead-service:
      url: http://${PROPERTY_LEAD_HOST:localhost}:${PROPERTY_LEAD_PORT:7103}
    property-mgmt-service:
      url: http://${PROPERTY_MGMT_HOST:localhost}:${PROPERTY_MGMT_PORT:7101}
    user-mgmt-service:
      url: http://${USER_MGMT_HOST:localhost}:${USER_MGMT_PORT:5051}
  properties:
    lead:
      topic: ${LEADS_TOPIC_NAME:property-lead}
  notifications:
    topic: notification-topic
server:
  port: 7104
eureka:
  client:
    service-url:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8761}/eureka/
  instance:
    hostname: ${REGISTRY_HOST:localhost}
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: ${REGISTRY_PREFER_IP:true}